version: 2
orbs:
  codecov: codecov/codecov@4.0.1
workflows:
  upload-to-codecov:
    jobs:
      - checkout
      - codecov/upload
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
        environment:
          JOBS: 1
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: git config --global user.email ${GH_USER_EMAIL}
      - run: git config --global user.name ${GH_USER_NAME}
      - run: sudo npm install -g greenkeeper-lockfile@1
      - run: sudo npm install -g lerna@8
      - restore_cache:
          keys:
          - deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          - deps-
      - run: npm ci
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths: 'node_modules'
      - run: npm run ci:before
      - run: npm run test:ci
      - run: if [ ${CIRCLE_BRANCH} == "master" ]; then lerna version --create-release github --yes; fi
      - run: npm run build:prod
      - run: npm run ci:after
      - run: if [ ${CIRCLE_BRANCH} == "master" ]; then lerna publish from-package --yes; fi
      - run: bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_artifacts:
          path: dist
          prefix: dist
      - store_test_results:
          path: test-report.xml
